-- Supabase Initial Schema Setup
-- This file documents the overall schema structure
-- Individual tables are created in separate migration files:
-- - 001_users_schema.sql: Users profile table (id, email, full_name, role)
-- - 002_subscriptions_schema.sql: Subscription management (plans, billing, trial periods)
-- - 003_analytics_schema.sql: Analytics data storage (metrics, regions, categories)
-- - 004_reports_schema.sql: AI-generated reports (scenario, analytics, custom reports)
-- - 005_update_subscriptions_new_pricing.sql: Updated pricing for enterprise plans
-- - 006_agencies_schema.sql: Agencies table (agency name, type, user association)

-- Note: This is a reference document. All actual schema creation is in the files above.
